# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'accueil.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Accueil(object):
    def setupUi(self, Accueil):
        Accueil.setObjectName("Accueil")
        Accueil.resize(716, 395)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(1)
        font.setBold(False)
        font.setWeight(50)
        Accueil.setFont(font)
        Accueil.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #FFE5B4;\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #FFDEAD;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    color: #FFDEAD;\n"
"    selection-background-color: #FFDEAD;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 1 #F28C28);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    color: #FFDEAD;;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    color: #FFDEAD;;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"}\n"
"QTableWidget::item:selected{ background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F); }\n"
"\n"
"QDateEdit\n"
"{\n"
"border : 2px solid #E49B0F;\n"
"background-color : QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);;\n"
"padding : 5px;\n"
"}\n"
"QDateEdit::up-arraow\n"
"{\n"
"border : 2px solid black;\n"
"background-color : lightgreen;\n"
"\n"
"}\n"
"QDateEdit::down-arrow\n"
"{\n"
"background-color : #E49B0F;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"   border: 1px solid #E49B0F;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background: #8B4000;\n"
"  color: white;\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: #E49B0F;\n"
" }\n"
"\n"
"QTabWidget::pane { \n"
"   border: none;\n"
"}")
        Accueil.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(Accueil)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_gest_user = QtWidgets.QPushButton(self.centralwidget)
        self.button_gest_user.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_gest_user.setFont(font)
        self.button_gest_user.setObjectName("button_gest_user")
        self.gridLayout.addWidget(self.button_gest_user, 6, 2, 1, 1)
        self.button_collectivite = QtWidgets.QPushButton(self.centralwidget)
        self.button_collectivite.setObjectName("button_collectivite")
        self.gridLayout.addWidget(self.button_collectivite, 1, 2, 1, 1)
        self.button_cotisation_dons = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_cotisation_dons.setFont(font)
        self.button_cotisation_dons.setObjectName("button_cotisation_dons")
        self.gridLayout.addWidget(self.button_cotisation_dons, 3, 1, 1, 1)
        self.button_about = QtWidgets.QPushButton(self.centralwidget)
        self.button_about.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_about.setFont(font)
        self.button_about.setObjectName("button_about")
        self.gridLayout.addWidget(self.button_about, 7, 2, 1, 1)
        self.button_adherents = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_adherents.setFont(font)
        self.button_adherents.setObjectName("button_adherents")
        self.gridLayout.addWidget(self.button_adherents, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.button_activite = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_activite.setFont(font)
        self.button_activite.setMouseTracking(False)
        self.button_activite.setObjectName("button_activite")
        self.gridLayout.addWidget(self.button_activite, 3, 2, 1, 1)
        self.button_gestion_devis = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_gestion_devis.setFont(font)
        self.button_gestion_devis.setObjectName("button_gestion_devis")
        self.gridLayout.addWidget(self.button_gestion_devis, 6, 1, 1, 1)
        self.label_logo = QtWidgets.QLabel(self.centralwidget)
        self.label_logo.setText("")
        self.label_logo.setObjectName("label_logo")
        self.gridLayout.addWidget(self.label_logo, 0, 0, 1, 1)
        self.button_gestion_facture = QtWidgets.QPushButton(self.centralwidget)
        self.button_gestion_facture.setObjectName("button_gestion_facture")
        self.gridLayout.addWidget(self.button_gestion_facture, 7, 1, 1, 1)
        Accueil.setCentralWidget(self.centralwidget)
        self.actionInformations = QtWidgets.QAction(Accueil)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/image/comment-info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInformations.setIcon(icon)
        self.actionInformations.setObjectName("actionInformations")
        self.actionNumerotation = QtWidgets.QAction(Accueil)
        self.actionNumerotation.setObjectName("actionNumerotation")
        self.actionGestion_des_exercices = QtWidgets.QAction(Accueil)
        self.actionGestion_des_exercices.setObjectName("actionGestion_des_exercices")
        self.actionListe_produits = QtWidgets.QAction(Accueil)
        self.actionListe_produits.setObjectName("actionListe_produits")
        self.actionAjouter_un_produit = QtWidgets.QAction(Accueil)
        self.actionAjouter_un_produit.setObjectName("actionAjouter_un_produit")
        self.actionListe_clients = QtWidgets.QAction(Accueil)
        self.actionListe_clients.setObjectName("actionListe_clients")
        self.actionAjouter_un_client = QtWidgets.QAction(Accueil)
        self.actionAjouter_un_client.setObjectName("actionAjouter_un_client")
        self.actionListe_des_fournisseurs = QtWidgets.QAction(Accueil)
        self.actionListe_des_fournisseurs.setObjectName("actionListe_des_fournisseurs")
        self.actionAjouter_un_fournisseur = QtWidgets.QAction(Accueil)
        self.actionAjouter_un_fournisseur.setObjectName("actionAjouter_un_fournisseur")
        self.actionTarifs = QtWidgets.QAction(Accueil)
        self.actionTarifs.setObjectName("actionTarifs")
        self.action_mode_reg = QtWidgets.QAction(Accueil)
        self.action_mode_reg.setObjectName("action_mode_reg")
        self.actionCivilites = QtWidgets.QAction(Accueil)
        self.actionCivilites.setObjectName("actionCivilites")
        self.actionConditions_de_paiement = QtWidgets.QAction(Accueil)
        self.actionConditions_de_paiement.setObjectName("actionConditions_de_paiement")

        self.retranslateUi(Accueil)
        QtCore.QMetaObject.connectSlotsByName(Accueil)

    def retranslateUi(self, Accueil):
        _translate = QtCore.QCoreApplication.translate
        Accueil.setWindowTitle(_translate("Accueil", "AssoGestion - Accueil - AMSE"))
        self.button_gest_user.setText(_translate("Accueil", "UTILISATEURS"))
        self.button_collectivite.setText(_translate("Accueil", "COLLECTIVITES"))
        self.button_cotisation_dons.setText(_translate("Accueil", "COTISATIONS"))
        self.button_about.setText(_translate("Accueil", "A PROPOS"))
        self.button_adherents.setText(_translate("Accueil", "ADHERENTS"))
        self.label.setText(_translate("Accueil", "ASSOGESTION - AMSE"))
        self.button_activite.setText(_translate("Accueil", "ACTIVITES"))
        self.button_gestion_devis.setText(_translate("Accueil", "DEVIS CLIENTS"))
        self.button_gestion_facture.setText(_translate("Accueil", "FACTURES CLIENTS"))
        self.actionInformations.setText(_translate("Accueil", "Informations sociétés"))
        self.actionNumerotation.setText(_translate("Accueil", "Numérotation document"))
        self.actionGestion_des_exercices.setText(_translate("Accueil", "Gestion des exercices"))
        self.actionListe_produits.setText(_translate("Accueil", "Liste produits"))
        self.actionAjouter_un_produit.setText(_translate("Accueil", "Ajouter un produit"))
        self.actionListe_clients.setText(_translate("Accueil", "Liste clients"))
        self.actionAjouter_un_client.setText(_translate("Accueil", "Ajouter un client"))
        self.actionListe_des_fournisseurs.setText(_translate("Accueil", "Liste des fournisseurs"))
        self.actionAjouter_un_fournisseur.setText(_translate("Accueil", "Ajouter un fournisseur"))
        self.actionTarifs.setText(_translate("Accueil", "Tarifs"))
        self.action_mode_reg.setText(_translate("Accueil", "Mode de réglement"))
        self.actionCivilites.setText(_translate("Accueil", "Civilites"))
        self.actionConditions_de_paiement.setText(_translate("Accueil", "Conditions de paiement"))
