# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detail_adherent.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_detail_adherent(object):
    def setupUi(self, detail_adherent):
        detail_adherent.setObjectName("detail_adherent")
        detail_adherent.resize(902, 876)
        detail_adherent.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #FFE5B4;\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #FFDEAD;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    color: #FFDEAD;\n"
"    selection-background-color: #FFDEAD;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 1 #F28C28);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    color: #FFDEAD;;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    color: #FFDEAD;;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"}\n"
"QTableWidget::item:selected{ background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F); }\n"
"\n"
"QDateEdit\n"
"{\n"
"border : 2px solid #E49B0F;\n"
"background-color : QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);;\n"
"padding : 5px;\n"
"}\n"
"QDateEdit::up-arraow\n"
"{\n"
"border : 2px solid black;\n"
"background-color : lightgreen;\n"
"\n"
"}\n"
"QDateEdit::down-arrow\n"
"{\n"
"background-color : #E49B0F;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"   border: 1px solid #E49B0F;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background: #8B4000;\n"
"  color: white;\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: #E49B0F;\n"
" }\n"
"\n"
"QTabWidget::pane { \n"
"   border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(detail_adherent)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.butt_valider = QtWidgets.QPushButton(self.centralwidget)
        self.butt_valider.setObjectName("butt_valider")
        self.gridLayout.addWidget(self.butt_valider, 2, 1, 1, 1)
        self.tab_adherent = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_adherent.setEnabled(True)
        self.tab_adherent.setDocumentMode(False)
        self.tab_adherent.setObjectName("tab_adherent")
        self.tab_info = QtWidgets.QWidget()
        self.tab_info.setObjectName("tab_info")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_info)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_info)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.adresse_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.adresse_edit.setObjectName("adresse_edit")
        self.gridLayout_4.addWidget(self.adresse_edit, 0, 1, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 5, 0, 1, 1)
        self.cp_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.cp_edit.setObjectName("cp_edit")
        self.gridLayout_4.addWidget(self.cp_edit, 3, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_error_ville = QtWidgets.QLabel(self.groupBox_2)
        self.label_error_ville.setStyleSheet("QLabel {\n"
"  color: rgb(255, 0, 0);\n"
"  font-weight: 600;\n"
"}")
        self.label_error_ville.setText("")
        self.label_error_ville.setObjectName("label_error_ville")
        self.gridLayout_4.addWidget(self.label_error_ville, 6, 0, 1, 3)
        self.label_error_adresse = QtWidgets.QLabel(self.groupBox_2)
        self.label_error_adresse.setStyleSheet("QLabel {\n"
"  color: rgb(255, 0, 0);\n"
"  font-weight: 600;\n"
"}")
        self.label_error_adresse.setText("")
        self.label_error_adresse.setObjectName("label_error_adresse")
        self.gridLayout_4.addWidget(self.label_error_adresse, 2, 1, 1, 3)
        self.cb_ville = QtWidgets.QComboBox(self.groupBox_2)
        self.cb_ville.setObjectName("cb_ville")
        self.gridLayout_4.addWidget(self.cb_ville, 5, 1, 1, 2)
        self.label_error_cp = QtWidgets.QLabel(self.groupBox_2)
        self.label_error_cp.setStyleSheet("QLabel {\n"
"  color: rgb(255, 0, 0);\n"
"  font-weight: 600;\n"
"}")
        self.label_error_cp.setText("")
        self.label_error_cp.setObjectName("label_error_cp")
        self.gridLayout_4.addWidget(self.label_error_cp, 4, 0, 1, 3)
        self.adress_comp_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.adress_comp_edit.setObjectName("adress_comp_edit")
        self.gridLayout_4.addWidget(self.adress_comp_edit, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.tab_info)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 3, 0, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.tab_info)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_2.addWidget(self.textEdit, 3, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_info)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 7, 0, 1, 1)
        self.nom_edit = QtWidgets.QLineEdit(self.groupBox)
        self.nom_edit.setEnabled(True)
        self.nom_edit.setObjectName("nom_edit")
        self.gridLayout_3.addWidget(self.nom_edit, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.code_edit = QtWidgets.QLineEdit(self.groupBox)
        self.code_edit.setEnabled(False)
        self.code_edit.setObjectName("code_edit")
        self.gridLayout_3.addWidget(self.code_edit, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_error_email = QtWidgets.QLabel(self.groupBox)
        self.label_error_email.setStyleSheet("QLabel {\n"
"  color: rgb(255, 0, 0);\n"
"  font-weight: 600;\n"
"}")
        self.label_error_email.setText("")
        self.label_error_email.setObjectName("label_error_email")
        self.gridLayout_3.addWidget(self.label_error_email, 12, 1, 1, 1)
        self.label_error_titre = QtWidgets.QLabel(self.groupBox)
        self.label_error_titre.setStyleSheet("QLabel {\n"
"  color: rgb(255, 0, 0);\n"
"  font-weight: 600;\n"
"}")
        self.label_error_titre.setText("")
        self.label_error_titre.setObjectName("label_error_titre")
        self.gridLayout_3.addWidget(self.label_error_titre, 3, 1, 1, 1)
        self.label_error_nom = QtWidgets.QLabel(self.groupBox)
        self.label_error_nom.setStyleSheet("QLabel {\n"
"  color: rgb(255, 0, 0);\n"
"  font-weight: 600;\n"
"}")
        self.label_error_nom.setText("")
        self.label_error_nom.setObjectName("label_error_nom")
        self.gridLayout_3.addWidget(self.label_error_nom, 6, 1, 1, 1)
        self.prenom_edit = QtWidgets.QLineEdit(self.groupBox)
        self.prenom_edit.setObjectName("prenom_edit")
        self.gridLayout_3.addWidget(self.prenom_edit, 7, 1, 1, 1)
        self.label_error_prenom = QtWidgets.QLabel(self.groupBox)
        self.label_error_prenom.setStyleSheet("QLabel {\n"
"  color: rgb(255, 0, 0);\n"
"  font-weight: 600;\n"
"}")
        self.label_error_prenom.setText("")
        self.label_error_prenom.setObjectName("label_error_prenom")
        self.gridLayout_3.addWidget(self.label_error_prenom, 8, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 9, 0, 1, 1)
        self.tel_edit = QtWidgets.QLineEdit(self.groupBox)
        self.tel_edit.setObjectName("tel_edit")
        self.gridLayout_3.addWidget(self.tel_edit, 9, 1, 1, 1)
        self.email_edit = QtWidgets.QLineEdit(self.groupBox)
        self.email_edit.setObjectName("email_edit")
        self.gridLayout_3.addWidget(self.email_edit, 11, 1, 1, 1)
        self.cb_titre = QtWidgets.QComboBox(self.groupBox)
        self.cb_titre.setObjectName("cb_titre")
        self.gridLayout_3.addWidget(self.cb_titre, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 11, 0, 1, 1)
        self.fonction_edit = QtWidgets.QLineEdit(self.groupBox)
        self.fonction_edit.setObjectName("fonction_edit")
        self.gridLayout_3.addWidget(self.fonction_edit, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_info)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 8, 0, 1, 1)
        self.cb_paiement_means = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_paiement_means.setObjectName("cb_paiement_means")
        self.cb_paiement_means.addItem("")
        self.cb_paiement_means.setItemText(0, "")
        self.cb_paiement_means.addItem("")
        self.cb_paiement_means.addItem("")
        self.cb_paiement_means.addItem("")
        self.cb_paiement_means.addItem("")
        self.gridLayout_5.addWidget(self.cb_paiement_means, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.adhesion_edit = QtWidgets.QDateEdit(self.groupBox_3)
        self.adhesion_edit.setCalendarPopup(True)
        self.adhesion_edit.setObjectName("adhesion_edit")
        self.gridLayout_5.addWidget(self.adhesion_edit, 5, 0, 1, 1)
        self.naissance_edit = QtWidgets.QDateEdit(self.groupBox_3)
        self.naissance_edit.setCalendarPopup(True)
        self.naissance_edit.setObjectName("naissance_edit")
        self.gridLayout_5.addWidget(self.naissance_edit, 1, 0, 1, 1)
        self.prospection_edit = QtWidgets.QDateEdit(self.groupBox_3)
        self.prospection_edit.setCalendarPopup(True)
        self.prospection_edit.setObjectName("prospection_edit")
        self.gridLayout_5.addWidget(self.prospection_edit, 3, 0, 1, 1)
        self.cb_type_membre = QtWidgets.QComboBox(self.groupBox_3)
        self.cb_type_membre.setObjectName("cb_type_membre")
        self.cb_type_membre.addItem("")
        self.cb_type_membre.setItemText(0, "")
        self.cb_type_membre.addItem("")
        self.cb_type_membre.addItem("")
        self.cb_type_membre.addItem("")
        self.gridLayout_5.addWidget(self.cb_type_membre, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 6, 0, 1, 1)
        self.check_bulletin = QtWidgets.QCheckBox(self.groupBox_3)
        self.check_bulletin.setObjectName("check_bulletin")
        self.gridLayout_5.addWidget(self.check_bulletin, 10, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 2, 1, 1)
        self.tab_adherent.addTab(self.tab_info, "")
        self.tab_adhesion = QtWidgets.QWidget()
        self.tab_adhesion.setObjectName("tab_adhesion")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_adhesion)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tab_adh_dons = QtWidgets.QTableWidget(self.tab_adhesion)
        self.tab_adh_dons.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_adh_dons.setObjectName("tab_adh_dons")
        self.tab_adh_dons.setColumnCount(0)
        self.tab_adh_dons.setRowCount(0)
        self.gridLayout_6.addWidget(self.tab_adh_dons, 2, 0, 1, 1)
        self.button_add_don = QtWidgets.QPushButton(self.tab_adhesion)
        self.button_add_don.setObjectName("button_add_don")
        self.gridLayout_6.addWidget(self.button_add_don, 1, 0, 1, 1)
        self.button_add_adh = QtWidgets.QPushButton(self.tab_adhesion)
        self.button_add_adh.setObjectName("button_add_adh")
        self.gridLayout_6.addWidget(self.button_add_adh, 0, 0, 1, 1)
        self.tab_adherent.addTab(self.tab_adhesion, "")
        self.tab_act = QtWidgets.QWidget()
        self.tab_act.setObjectName("tab_act")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_act)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tab_activites_adherent = QtWidgets.QTableWidget(self.tab_act)
        self.tab_activites_adherent.setObjectName("tab_activites_adherent")
        self.tab_activites_adherent.setColumnCount(3)
        self.tab_activites_adherent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tab_activites_adherent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_activites_adherent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tab_activites_adherent.setHorizontalHeaderItem(2, item)
        self.gridLayout_7.addWidget(self.tab_activites_adherent, 0, 0, 1, 1)
        self.tab_adherent.addTab(self.tab_act, "")
        self.gridLayout.addWidget(self.tab_adherent, 1, 0, 1, 2)
        self.button_retour = QtWidgets.QPushButton(self.centralwidget)
        self.button_retour.setObjectName("button_retour")
        self.gridLayout.addWidget(self.button_retour, 2, 0, 1, 1)
        detail_adherent.setCentralWidget(self.centralwidget)

        self.retranslateUi(detail_adherent)
        self.tab_adherent.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(detail_adherent)
        detail_adherent.setTabOrder(self.code_edit, self.cb_titre)
        detail_adherent.setTabOrder(self.cb_titre, self.fonction_edit)
        detail_adherent.setTabOrder(self.fonction_edit, self.nom_edit)
        detail_adherent.setTabOrder(self.nom_edit, self.prenom_edit)
        detail_adherent.setTabOrder(self.prenom_edit, self.tel_edit)
        detail_adherent.setTabOrder(self.tel_edit, self.email_edit)
        detail_adherent.setTabOrder(self.email_edit, self.adresse_edit)
        detail_adherent.setTabOrder(self.adresse_edit, self.adress_comp_edit)
        detail_adherent.setTabOrder(self.adress_comp_edit, self.cp_edit)
        detail_adherent.setTabOrder(self.cp_edit, self.cb_ville)
        detail_adherent.setTabOrder(self.cb_ville, self.naissance_edit)
        detail_adherent.setTabOrder(self.naissance_edit, self.prospection_edit)
        detail_adherent.setTabOrder(self.prospection_edit, self.adhesion_edit)
        detail_adherent.setTabOrder(self.adhesion_edit, self.cb_type_membre)
        detail_adherent.setTabOrder(self.cb_type_membre, self.textEdit)
        detail_adherent.setTabOrder(self.textEdit, self.button_retour)
        detail_adherent.setTabOrder(self.button_retour, self.butt_valider)
        detail_adherent.setTabOrder(self.butt_valider, self.button_add_adh)
        detail_adherent.setTabOrder(self.button_add_adh, self.tab_adh_dons)
        detail_adherent.setTabOrder(self.tab_adh_dons, self.tab_adherent)

    def retranslateUi(self, detail_adherent):
        _translate = QtCore.QCoreApplication.translate
        detail_adherent.setWindowTitle(_translate("detail_adherent", "AssoGestion - Détail adhérent - AMSE"))
        self.butt_valider.setText(_translate("detail_adherent", "SAUVER"))
        self.label_5.setText(_translate("detail_adherent", "ADRESSE"))
        self.label_7.setText(_translate("detail_adherent", "VILLE"))
        self.label_6.setText(_translate("detail_adherent", "CP"))
        self.label_14.setText(_translate("detail_adherent", "COMMENTAIRE"))
        self.label_2.setText(_translate("detail_adherent", "NOM"))
        self.label_3.setText(_translate("detail_adherent", "PRENOM"))
        self.label.setText(_translate("detail_adherent", "TITRE"))
        self.label_15.setText(_translate("detail_adherent", "CODE ADHERENT"))
        self.label_4.setText(_translate("detail_adherent", "TELEPHONE"))
        self.label_8.setText(_translate("detail_adherent", "EMAIL"))
        self.label_16.setText(_translate("detail_adherent", "FONCTION"))
        self.label_13.setText(_translate("detail_adherent", "MOYEN DE PAIEMENT"))
        self.cb_paiement_means.setItemText(1, _translate("detail_adherent", "Chèque"))
        self.cb_paiement_means.setItemText(2, _translate("detail_adherent", "Espèce"))
        self.cb_paiement_means.setItemText(3, _translate("detail_adherent", "CB"))
        self.cb_paiement_means.setItemText(4, _translate("detail_adherent", "Virement"))
        self.label_11.setText(_translate("detail_adherent", "DATE DE REGLEMENT"))
        self.label_9.setText(_translate("detail_adherent", "DATE DE NAISSANCE"))
        self.label_10.setText(_translate("detail_adherent", "DATE DE PROSPECTION"))
        self.adhesion_edit.setDisplayFormat(_translate("detail_adherent", "dd/MM/yyyy"))
        self.naissance_edit.setDisplayFormat(_translate("detail_adherent", "dd/MM/yyyy"))
        self.prospection_edit.setDisplayFormat(_translate("detail_adherent", "dd/MM/yyyy"))
        self.cb_type_membre.setItemText(1, _translate("detail_adherent", "Membre"))
        self.cb_type_membre.setItemText(2, _translate("detail_adherent", "Ancien Membre"))
        self.cb_type_membre.setItemText(3, _translate("detail_adherent", "Prospect"))
        self.label_12.setText(_translate("detail_adherent", "CATEGORIE"))
        self.check_bulletin.setText(_translate("detail_adherent", "BULLETIN"))
        self.tab_adherent.setTabText(self.tab_adherent.indexOf(self.tab_info), _translate("detail_adherent", "INFORMATIONS"))
        self.button_add_don.setText(_translate("detail_adherent", "AJOUTER UN DON"))
        self.button_add_adh.setText(_translate("detail_adherent", "AJOUTER UNE ADHESION"))
        self.tab_adherent.setTabText(self.tab_adherent.indexOf(self.tab_adhesion), _translate("detail_adherent", "ADHESIONS ET DONS"))
        item = self.tab_activites_adherent.horizontalHeaderItem(0)
        item.setText(_translate("detail_adherent", "Code"))
        item = self.tab_activites_adherent.horizontalHeaderItem(1)
        item.setText(_translate("detail_adherent", "Activité"))
        item = self.tab_activites_adherent.horizontalHeaderItem(2)
        item.setText(_translate("detail_adherent", "Date"))
        self.tab_adherent.setTabText(self.tab_adherent.indexOf(self.tab_act), _translate("detail_adherent", "ACTIVITES"))
        self.button_retour.setText(_translate("detail_adherent", "RETOUR"))
