# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ligne_facture.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_ligne_facture(object):
    def setupUi(self, ligne_facture):
        ligne_facture.setObjectName("ligne_facture")
        ligne_facture.resize(501, 262)
        ligne_facture.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #FFE5B4;\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #FFDEAD;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    color: #FFDEAD;\n"
"    selection-background-color: #FFDEAD;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 1 #F28C28);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    color: #FFDEAD;;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    color: #FFDEAD;;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"}\n"
"QTableWidget::item:selected{ background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F); }\n"
"\n"
"QDateEdit\n"
"{\n"
"border : 2px solid #E49B0F;\n"
"background-color : QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);;\n"
"padding : 5px;\n"
"}\n"
"QDateEdit::up-arraow\n"
"{\n"
"border : 2px solid black;\n"
"background-color : lightgreen;\n"
"\n"
"}\n"
"QDateEdit::down-arrow\n"
"{\n"
"background-color : #E49B0F;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"   border: 1px solid #E49B0F;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background: #8B4000;\n"
"  color: white;\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: #E49B0F;\n"
" }\n"
"\n"
"QTabWidget::pane { \n"
"   border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(ligne_facture)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.spin_pu = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_pu.setMaximum(999999.0)
        self.spin_pu.setObjectName("spin_pu")
        self.gridLayout.addWidget(self.spin_pu, 3, 2, 1, 1)
        self.code_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.code_edit.setEnabled(True)
        self.code_edit.setObjectName("code_edit")
        self.gridLayout.addWidget(self.code_edit, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.button_ok = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok.setObjectName("button_ok")
        self.gridLayout.addWidget(self.button_ok, 5, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spin_total = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_total.setEnabled(False)
        self.spin_total.setMaximum(999999.0)
        self.spin_total.setObjectName("spin_total")
        self.gridLayout.addWidget(self.spin_total, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.spin_qty = QtWidgets.QSpinBox(self.centralwidget)
        self.spin_qty.setMaximum(99999999)
        self.spin_qty.setObjectName("spin_qty")
        self.gridLayout.addWidget(self.spin_qty, 2, 2, 1, 1)
        self.button_delete = QtWidgets.QPushButton(self.centralwidget)
        self.button_delete.setObjectName("button_delete")
        self.gridLayout.addWidget(self.button_delete, 6, 2, 1, 1)
        self.desc_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.desc_edit.setObjectName("desc_edit")
        self.gridLayout.addWidget(self.desc_edit, 1, 2, 1, 1)
        ligne_facture.setCentralWidget(self.centralwidget)

        self.retranslateUi(ligne_facture)
        QtCore.QMetaObject.connectSlotsByName(ligne_facture)
        ligne_facture.setTabOrder(self.code_edit, self.spin_qty)
        ligne_facture.setTabOrder(self.spin_qty, self.spin_pu)
        ligne_facture.setTabOrder(self.spin_pu, self.spin_total)
        ligne_facture.setTabOrder(self.spin_total, self.button_ok)

    def retranslateUi(self, ligne_facture):
        _translate = QtCore.QCoreApplication.translate
        ligne_facture.setWindowTitle(_translate("ligne_facture", "AssoGestion - Ligne facture - AMSE"))
        self.label_5.setText(_translate("ligne_facture", "TOTAL HT"))
        self.button_ok.setText(_translate("ligne_facture", "OK"))
        self.label.setText(_translate("ligne_facture", "CODE"))
        self.label_3.setText(_translate("ligne_facture", "QUANTITE"))
        self.label_2.setText(_translate("ligne_facture", "DESCRIPTION"))
        self.label_4.setText(_translate("ligne_facture", "PRIX HT"))
        self.button_delete.setText(_translate("ligne_facture", "SUPPRIMER LA LIGNE"))
