# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'liste_adherents.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_liste_adherent(object):
    def setupUi(self, liste_adherent):
        liste_adherent.setObjectName("liste_adherent")
        liste_adherent.resize(1003, 484)
        liste_adherent.setStyleSheet("QWidget\n"
"{\n"
"    background-color: #FFE5B4;\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: #FFDEAD;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    font-size: 12px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    min-width: 40px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    color: #FFDEAD;\n"
"    selection-background-color: #FFDEAD;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 1 #F28C28);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    color: #FFDEAD;;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"    color: #FFDEAD;;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
"}\n"
"QTableWidget::item:selected{ background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F); }\n"
"\n"
"QDateEdit\n"
"{\n"
"border : 2px solid #E49B0F;\n"
"background-color : QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);;\n"
"padding : 5px;\n"
"}\n"
"QDateEdit::up-arraow\n"
"{\n"
"border : 2px solid black;\n"
"background-color : lightgreen;\n"
"\n"
"}\n"
"QDateEdit::down-arrow\n"
"{\n"
"background-color : #E49B0F;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"   border: 1px solid #E49B0F;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background: #8B4000;\n"
"  color: white;\n"
"  padding: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background: #E49B0F;\n"
" }\n"
"\n"
"QTabWidget::pane { \n"
"   border: none;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(liste_adherent)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.button_retour = QtWidgets.QPushButton(self.centralwidget)
        self.button_retour.setObjectName("button_retour")
        self.gridLayout.addWidget(self.button_retour, 0, 0, 1, 1)
        self.tab_adherent = QtWidgets.QTableWidget(self.centralwidget)
        self.tab_adherent.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tab_adherent.setObjectName("tab_adherent")
        self.tab_adherent.setColumnCount(0)
        self.tab_adherent.setRowCount(0)
        self.gridLayout.addWidget(self.tab_adherent, 2, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gb_import = QtWidgets.QGroupBox(self.groupBox)
        self.gb_import.setObjectName("gb_import")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gb_import)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.button_import_adherent = QtWidgets.QPushButton(self.gb_import)
        self.button_import_adherent.setObjectName("button_import_adherent")
        self.gridLayout_4.addWidget(self.button_import_adherent, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gb_import, 0, 2, 1, 1)
        self.gb_creation = QtWidgets.QGroupBox(self.groupBox)
        self.gb_creation.setObjectName("gb_creation")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gb_creation)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.button_creation_adherents = QtWidgets.QPushButton(self.gb_creation)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/sign-in-alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_creation_adherents.setIcon(icon)
        self.button_creation_adherents.setObjectName("button_creation_adherents")
        self.gridLayout_3.addWidget(self.button_creation_adherents, 0, 0, 1, 1)
        self.button_creation_prospect = QtWidgets.QPushButton(self.gb_creation)
        self.button_creation_prospect.setObjectName("button_creation_prospect")
        self.gridLayout_3.addWidget(self.button_creation_prospect, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gb_creation, 0, 0, 2, 2)
        self.gb_action = QtWidgets.QGroupBox(self.groupBox)
        self.gb_action.setObjectName("gb_action")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gb_action)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.button_send_recu = QtWidgets.QPushButton(self.gb_action)
        self.button_send_recu.setObjectName("button_send_recu")
        self.gridLayout_5.addWidget(self.button_send_recu, 0, 0, 1, 1)
        self.button_send_mail = QtWidgets.QPushButton(self.gb_action)
        self.button_send_mail.setObjectName("button_send_mail")
        self.gridLayout_5.addWidget(self.button_send_mail, 1, 0, 1, 1)
        self.button_export_adherents = QtWidgets.QPushButton(self.gb_action)
        self.button_export_adherents.setObjectName("button_export_adherents")
        self.gridLayout_5.addWidget(self.button_export_adherents, 2, 0, 1, 1)
        self.button_maj_membre = QtWidgets.QPushButton(self.gb_action)
        self.button_maj_membre.setObjectName("button_maj_membre")
        self.gridLayout_5.addWidget(self.button_maj_membre, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.gb_action, 0, 3, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.search_ville = QtWidgets.QLineEdit(self.groupBox_5)
        self.search_ville.setObjectName("search_ville")
        self.gridLayout_6.addWidget(self.search_ville, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 2, 0, 1, 1)
        self.search_cp = QtWidgets.QLineEdit(self.groupBox_5)
        self.search_cp.setObjectName("search_cp")
        self.gridLayout_6.addWidget(self.search_cp, 3, 1, 1, 1)
        self.search_email = QtWidgets.QLineEdit(self.groupBox_5)
        self.search_email.setObjectName("search_email")
        self.gridLayout_6.addWidget(self.search_email, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 4, 0, 1, 1)
        self.search_adresse = QtWidgets.QLineEdit(self.groupBox_5)
        self.search_adresse.setObjectName("search_adresse")
        self.gridLayout_6.addWidget(self.search_adresse, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.search_nom = QtWidgets.QLineEdit(self.groupBox_5)
        self.search_nom.setObjectName("search_nom")
        self.gridLayout_6.addWidget(self.search_nom, 0, 1, 1, 1)
        self.search_prenom = QtWidgets.QLineEdit(self.groupBox_5)
        self.search_prenom.setObjectName("search_prenom")
        self.gridLayout_6.addWidget(self.search_prenom, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 5, 0, 1, 1)
        self.search_tel = QtWidgets.QLineEdit(self.groupBox_5)
        self.search_tel.setObjectName("search_tel")
        self.gridLayout_6.addWidget(self.search_tel, 6, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_5, 4, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.cb_cat_membre = QtWidgets.QComboBox(self.groupBox_6)
        self.cb_cat_membre.setObjectName("cb_cat_membre")
        self.gridLayout_7.addWidget(self.cb_cat_membre, 1, 1, 1, 1)
        self.cb_type_membre = QtWidgets.QComboBox(self.groupBox_6)
        self.cb_type_membre.setObjectName("cb_type_membre")
        self.cb_type_membre.addItem("")
        self.cb_type_membre.setItemText(0, "")
        self.cb_type_membre.addItem("")
        self.cb_type_membre.addItem("")
        self.cb_type_membre.addItem("")
        self.gridLayout_7.addWidget(self.cb_type_membre, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_6, 4, 2, 1, 2)
        self.button_rechercher = QtWidgets.QPushButton(self.groupBox)
        self.button_rechercher.setObjectName("button_rechercher")
        self.gridLayout_2.addWidget(self.button_rechercher, 5, 3, 1, 1)
        self.label_res_search = QtWidgets.QLabel(self.groupBox)
        self.label_res_search.setObjectName("label_res_search")
        self.gridLayout_2.addWidget(self.label_res_search, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        liste_adherent.setCentralWidget(self.centralwidget)

        self.retranslateUi(liste_adherent)
        QtCore.QMetaObject.connectSlotsByName(liste_adherent)

    def retranslateUi(self, liste_adherent):
        _translate = QtCore.QCoreApplication.translate
        liste_adherent.setWindowTitle(_translate("liste_adherent", "AssoGestion - Liste adhérents - AMSE"))
        self.button_retour.setText(_translate("liste_adherent", "RETOUR"))
        self.tab_adherent.setSortingEnabled(True)
        self.gb_import.setTitle(_translate("liste_adherent", "Import"))
        self.button_import_adherent.setText(_translate("liste_adherent", "IMPORTER LES ADHERENTS"))
        self.gb_creation.setTitle(_translate("liste_adherent", "Création"))
        self.button_creation_adherents.setText(_translate("liste_adherent", "CREER UN ADHERENT"))
        self.button_creation_prospect.setText(_translate("liste_adherent", "CREER UN PROSPECT"))
        self.gb_action.setTitle(_translate("liste_adherent", "Actions"))
        self.button_send_recu.setText(_translate("liste_adherent", "ENVOI RECU FISCAUX"))
        self.button_send_mail.setText(_translate("liste_adherent", "ENVOI EMAIL"))
        self.button_export_adherents.setText(_translate("liste_adherent", "EXPORTER LES ADHERENTS"))
        self.button_maj_membre.setText(_translate("liste_adherent", "METTRE A JOUR LES MEMBRES"))
        self.groupBox_5.setTitle(_translate("liste_adherent", "RECHERCHE TEXTUELLE"))
        self.label_4.setText(_translate("liste_adherent", "ADRESSE"))
        self.label_3.setText(_translate("liste_adherent", "PRENOM"))
        self.label_5.setText(_translate("liste_adherent", "CP"))
        self.label_6.setText(_translate("liste_adherent", "VILLE"))
        self.label.setText(_translate("liste_adherent", "NOM"))
        self.label_7.setText(_translate("liste_adherent", "EMAIL"))
        self.label_8.setText(_translate("liste_adherent", "TELEPHONE"))
        self.groupBox_6.setTitle(_translate("liste_adherent", "FILTRE"))
        self.label_2.setText(_translate("liste_adherent", "TYPE DE MEMBRE"))
        self.cb_type_membre.setItemText(1, _translate("liste_adherent", "Membre"))
        self.cb_type_membre.setItemText(2, _translate("liste_adherent", "Ancien Membre"))
        self.cb_type_membre.setItemText(3, _translate("liste_adherent", "Prospect"))
        self.label_9.setText(_translate("liste_adherent", "CATEGORIE DE MEMBRE"))
        self.button_rechercher.setText(_translate("liste_adherent", "RECHERCHER"))
        self.label_res_search.setText(_translate("liste_adherent", "LA RECHERCHE RETOURNE X RESULTAT(S)"))
