C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe connexion.ui -o connexion.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe accueil.ui -o accueil.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe liste_adherents.ui -o liste_adherents.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe liste_collectivite.ui -o liste_collectivite.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe detail_adherent.ui -o detail_adherent.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe detail_collectivite.ui -o detail_collectivite.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe fic_ind.ui -o fic_ind.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe fic_recu_ind.ui -o fic_recu_ind.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe liste_tarif.ui -o liste_tarif.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe detail_cot.ui -o detail_cot.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe adh_cot.ui -o adh_cot.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe coll_cot.ui -o coll_cot.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe pop_up_dev_fac.ui -o pop_up_dev_fac.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe pop_up_part.ui -o pop_up_part.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe liste_activite.ui -o liste_activite.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe detail_activite.ui -o detail_activite.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe activite_add_adh.ui -o activite_add_adh.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe mailing.ui -o mailing.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe devis.ui -o devis.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe liste_devis.ui -o liste_devis.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe facture.ui -o facture.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe liste_facture.ui -o liste_facture.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe ligne_devis.ui -o ligne_devis.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe ligne_facture.ui -o ligne_facture.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe gest_user.ui -o gest_user.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe detail_user.ui -o detail_user.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe search_ville.ui -o search_ville.py
C:\Users\aboucher\AppData\Local\Programs\Python\Python310\Scripts\pyuic5.exe pop_up.ui -o pop_up.py