from PyQt5.QtWidgets import QMessageBox


def pop_up(self, title, texte, info_texte, level):
    msgbox = QMessageBox()
    msgbox.setWindowIcon(self.icon)
    msgbox.setStyleSheet("QWidget\n"
                         "{\n"
                         "    background-color: #FFE5B4;\n"
                         "}\n"
                         "\n"
                         "QLineEdit\n"
                         "{\n"
                         "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);\n"
                         "    padding: 1px;\n"
                         "    border-style: solid;\n"
                         "    border: 1px solid #1e1e1e;\n"
                         "    border-radius: 5;\n"
                         "}\n"
                         "\n"
                         "QPushButton\n"
                         "{\n"
                         "    color: #FFDEAD;\n"
                         "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
                         "    border-width: 1px;\n"
                         "    border-color: #1e1e1e;\n"
                         "    border-style: solid;\n"
                         "    border-radius: 6;\n"
                         "    padding: 3px;\n"
                         "    font-size: 12px;\n"
                         "    padding-left: 5px;\n"
                         "    padding-right: 5px;\n"
                         "    min-width: 40px;\n"
                         "}\n"
                         "\n"
                         "QPushButton:pressed\n"
                         "{\n"
                         "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
                         "}\n"
                         "\n"
                         "QComboBox\n"
                         "{\n"
                         "    color: #FFDEAD;\n"
                         "    selection-background-color: #FFDEAD;\n"
                         "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
                         "    border-style: solid;\n"
                         "    border: 1px solid #1e1e1e;\n"
                         "    border-radius: 5;\n"
                         "}\n"
                         "\n"
                         "QComboBox:hover,QPushButton:hover\n"
                         "{\n"
                         "    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 1 #F28C28);\n"
                         "}\n"
                         "\n"
                         "\n"
                         "QComboBox:on\n"
                         "{\n"
                         "    padding-top: 3px;\n"
                         "    padding-left: 4px;\n"
                         "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
                         "    selection-background-color: #ffaa00;\n"
                         "}\n"
                         "\n"
                         "QComboBox QAbstractItemView\n"
                         "{\n"
                         "    border: 2px solid darkgray;\n"
                         "    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                         "}\n"
                         "\n"
                         "QComboBox::drop-down\n"
                         "{\n"
                         "     subcontrol-origin: padding;\n"
                         "     subcontrol-position: top right;\n"
                         "     width: 15px;\n"
                         "\n"
                         "     border-left-width: 0px;\n"
                         "     border-left-color: darkgray;\n"
                         "     border-left-style: solid; /* just a single line */\n"
                         "     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
                         "     border-bottom-right-radius: 3px;\n"
                         " }\n"
                         "\n"
                         "\n"
                         "QScrollBar:horizontal {\n"
                         "     border: 1px solid #222222;\n"
                         "     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
                         "     height: 7px;\n"
                         "     margin: 0px 16px 0 16px;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::handle:horizontal\n"
                         "{\n"
                         "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
                         "      min-height: 20px;\n"
                         "      border-radius: 2px;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::add-line:horizontal {\n"
                         "      border: 1px solid #1b1b19;\n"
                         "      border-radius: 2px;\n"
                         "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                         "      width: 14px;\n"
                         "      subcontrol-position: right;\n"
                         "      subcontrol-origin: margin;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::sub-line:horizontal {\n"
                         "      border: 1px solid #1b1b19;\n"
                         "      border-radius: 2px;\n"
                         "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                         "      width: 14px;\n"
                         "     subcontrol-position: left;\n"
                         "     subcontrol-origin: margin;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
                         "{\n"
                         "      border: 1px solid black;\n"
                         "      width: 1px;\n"
                         "      height: 1px;\n"
                         "      background: white;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
                         "{\n"
                         "      background: none;\n"
                         "}\n"
                         "\n"
                         "QScrollBar:vertical\n"
                         "{\n"
                         "      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
                         "      width: 7px;\n"
                         "      margin: 16px 0 16px 0;\n"
                         "      border: 1px solid #222222;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::handle:vertical\n"
                         "{\n"
                         "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
                         "      min-height: 20px;\n"
                         "      border-radius: 2px;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::add-line:vertical\n"
                         "{\n"
                         "      border: 1px solid #1b1b19;\n"
                         "      border-radius: 2px;\n"
                         "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
                         "      height: 14px;\n"
                         "      subcontrol-position: bottom;\n"
                         "      subcontrol-origin: margin;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::sub-line:vertical\n"
                         "{\n"
                         "      border: 1px solid #1b1b19;\n"
                         "      border-radius: 2px;\n"
                         "      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
                         "      height: 14px;\n"
                         "      subcontrol-position: top;\n"
                         "      subcontrol-origin: margin;\n"
                         "}\n"
                         "\n"
                         "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
                         "{\n"
                         "      border: 1px solid black;\n"
                         "      width: 1px;\n"
                         "      height: 1px;\n"
                         "      background: white;\n"
                         "}\n"
                         "\n"
                         "\n"
                         "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
                         "{\n"
                         "      background: none;\n"
                         "}\n"
                         "\n"
                         "QHeaderView::section:horizontal\n"
                         "{\n"
                         "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
                         "    color: #FFDEAD;;\n"
                         "    padding-left: 4px;\n"
                         "    border: 1px solid #6c6c6c;\n"
                         "}\n"
                         "QHeaderView::section:vertical\n"
                         "{\n"
                         "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
                         "    color: #FFDEAD;;\n"
                         "    padding-left: 4px;\n"
                         "    border: 1px solid #6c6c6c;\n"
                         "}\n"
                         "QTableWidget QTableCornerButton::section {\n"
                         "    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFAC1C, stop: 0.1 #F28C28, stop: 0.5 #B87333, stop: 0.9 #8B4000, stop: 1 #464646);\n"
                         "}\n"
                         "QTableWidget::item:selected{ background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F); }\n"
                         "\n"
                         "QDateEdit\n"
                         "{\n"
                         "border : 2px solid #E49B0F;\n"
                         "background-color : QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #FFDEAD, stop: 0.1 #FAD5A5, stop: 0.5 #F4BB44, stop: 0.9 #FFAC1C, stop: 1 #E49B0F);;\n"
                         "padding : 5px;\n"
                         "}\n"
                         "QDateEdit::up-arraow\n"
                         "{\n"
                         "border : 2px solid black;\n"
                         "background-color : lightgreen;\n"
                         "\n"
                         "}\n"
                         "QDateEdit::down-arrow\n"
                         "{\n"
                         "background-color : #E49B0F;\n"
                         "}\n"
                         "\n"
                         "QTabWidget::tab-bar {\n"
                         "   border: 1px solid #E49B0F;\n"
                         "}\n"
                         "\n"
                         "QTabBar::tab {\n"
                         "  background: #8B4000;\n"
                         "  color: white;\n"
                         "  padding: 10px;\n"
                         " }\n"
                         "\n"
                         " QTabBar::tab:selected {\n"
                         "  background: #E49B0F;\n"
                         " }\n"
                         "\n"
                         "QTabWidget::pane { \n"
                         "   border: none;\n"
                         "}")

    msgbox.setText(texte)
    msgbox.setWindowTitle(title)
    msgbox.setInformativeText(info_texte)
    if level == "INFO":
        msgbox.setIcon(QMessageBox.Information)
    elif level == "WARNING":
        msgbox.setIcon(QMessageBox.Warning)
    else:
        msgbox.setIcon(QMessageBox.Critical)
    msgbox.exec_()
